[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
monitor_dtr = 1
monitor_rts = 1
build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCONFIG_ESP_CONSOLE_USB_CDC=y
lib_deps = 
    adafruit/RTClib@^2.1.2
    adafruit/Adafruit Unified Sensor@^1.1.9
    adafruit/Adafruit BusIO@^1.14.5
    adafruit/Adafruit PWM Servo Driver Library@^2.4.1

